### ISSUE TITLE
function lp_main_box is not work for me

### ISSUE THREAD

**Issue by Lwan12** [Public-Health-Scotland/scotpho-profiles-tool#46]
Hi your code is prefect and I'm learning from your code. 
I copy your function lp_main_box in my code but it's not work , even the pictures cannot be displayed, and the path is right. 
This is my code :
`
library(rintrojs)
library(shiny)
ui <- shinyUI(fluidPage(
  introjsUI(), 
  mainPanel(
    introBox(
      div(class="landing-page-box",
          div("title_box", class = "landing-page-box-title"),
          div(class = "landing-page-icon", style= paste0("background-image: url(D:/chord_diagram.png);background-size: auto 80%; background-position: center; background-repeat: no-repeat;")),
          actionButton("btn", NULL, class="landing-page-button")),
      data.step = 1,
      data.intro = "hello"
    )
    
  )))

server <- shinyServer(function(input, output, session) {
  output$mtcars <- renderTable({
    head(mtcars)
  })
})
shinyApp(ui = ui, server = server)
`

Thanks

**Comment by jvillacampa** [comment]
Glad that the code is useful. I can see a couple of issues in your code:

- You are using classes (e.g. landing-page-box-title) that are not defined in your code. In our code these are defined in the file styles.css in the www folder. This file is sourced into the ui in line 24 of the tool ui script.
- Shiny prefers relative filepaths rather than absolute ones. You use a relative one (D:/chord_diagram.png). Ours are located in the www folder of the project where Shiny looks for media as default.

Hope that helps!

**Comment by Lwan12** [comment]
> Glad that the code is useful. I can see a couple of issues in your code:
> 
> * You are using classes (e.g. landing-page-box-title) that are not defined in your code. In our code these are defined in the file styles.css in the www folder. This file is sourced into the ui in line 24 of the tool ui script.
> * Shiny prefers relative filepaths rather than absolute ones. You use a relative one (D:/chord_diagram.png). Ours are located in the www folder of the project where Shiny looks for media as default.
> 
> Hope that helps!

Thanks for your help, my code ran successfully！
Your code has taught me a lot, thank you very much!
